server:
  port: 8181
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/project1
    driver-class-name: org.postgresql.Driver
    username: hydra
    password: ctrls.123
    hikari:
      auto-commit: on
      connection-timeout: 3000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/customer-service.xml