server:
  port: 8585
order:
  kafka:
    producer:
      bootstrap-servers:
        - http://localhost:9092
        - http://localhost:9093
        - http://localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: order-service-client
      number-of-retries: 3http://localhost:9092
      retries-backoff-ms-config: 1000
      max-request-size-config: 10000000
      acks-config: 1
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/project1
    driver-class-name: org.postgresql.Driver
    username: hydra
    password: ctrls.123
    hikari:
      auto-commit: on
      connection-timeout: 3000
  mvc:
    problemdetails:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/order-service-liquibase-changeLog.xml
payment:
  service:
    base-url: http://localhost:9091
    create-payment: payment/processPayment


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
  api-docs:
    path: /api-docs





logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"correlation-id\": \"%X{X-Correlation-Id}\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"